# Generated by Django 4.0.3 on 2022-04-17 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales_prospects', '0002_alter_salesprospectsprofile_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesProspectProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_user', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, default=None, max_length=100)),
                ('amount', models.CharField(max_length=11)),
                ('phone', models.CharField(max_length=14)),
                ('call', models.CharField(max_length=255)),
                ('nss', models.CharField(blank=True, max_length=11, null=True)),
                ('first_credit', models.BooleanField(default=True)),
                ('called', models.BooleanField(default=False)),
                ('sold', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner_prospect', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Prospect',
                'verbose_name_plural': 'Sales Prospects',
            },
        ),
        migrations.DeleteModel(
            name='SalesProspectsProfile',
        ),
    ]
