# Generated by Django 4.0.3 on 2022-04-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_prospects', '0004_alter_salesprospectprofile_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesprospectprofile',
            name='fb_user',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='salesprospectprofile',
            name='nss',
            field=models.CharField(blank=True, default='', max_length=11, null=True),
        ),
    ]
